//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EduTrack.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_SchoolManagementEntities : DbContext
    {
        public DB_SchoolManagementEntities()
            : base("name=DB_SchoolManagementEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Tbl_Attendance> Tbl_Attendance { get; set; }
        public virtual DbSet<Tbl_Exam> Tbl_Exam { get; set; }
        public virtual DbSet<Tbl_ExamMarks> Tbl_ExamMarks { get; set; }
        public virtual DbSet<Tbl_Student> Tbl_Student { get; set; }
        public virtual DbSet<Tbl_Subject> Tbl_Subject { get; set; }
        public virtual DbSet<Tbl_Teacher> Tbl_Teacher { get; set; }
        public virtual DbSet<Tbl_TimeTable> Tbl_TimeTable { get; set; }
    }
}
