//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EduTrack.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Attendance
    {
        public int AutoId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string StdID { get; set; }
        public Nullable<bool> IsAttendance { get; set; }
        public string Type { get; set; }
        public string Reason { get; set; }
    }
}
